<a href="https://colab.research.google.com/github/yunustalip/w1---work3/blob/main/w1_work_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
repeat = False
b = np.zeros((6,8),dtype='int32')
for i in range(0,6):
    for j in range(0,8):
        a = np.random.randint(1,50)
        if(a in b.T[j]):
            repeat = True
        while repeat == True:
            if(a in b.T[j]):
                a = np.random.randint(1,50)
                repeat = True
            else:
                repeat = False
        b[i][j] = a
            
print(b)

[[20 12 15 20 25 31 29 28]
 [47 10 43 43 29 47 23 32]
 [24 39 44 17 33 26 46 34]
 [18 13 39 10 11 17  5 24]
 [34 11 25 24 48 24 37 26]
 [35 32 22 45 45 49 16  4]]
